class TestUser(object):
    DEPARTURE_CITY = 'Wroclaw'
    DESTINATION_CITY = 'Glasgow'
    LOGIN = 'test.acc.ryan@gmail.com'
    PASS = 'Qwertyui1!'
    FIRST_NAME = 'TestFirstName'
    LAST_NAME = 'TestLastName'
    CARD_NUMBER = '2500000000000001'
    CVV = '123'
    CARD_HOLDER_NAME = 'TestName'
    TEST_ADDRESS_1 = 'TestAddress1'
    TEST_ADDRESS_2 = 'TestAddress2'
    CITY = 'TestCity'
    POSTCODE= '12345'
